const express = require("express")
const route = express.Router()
const loginController = require("./src/controllers/loginController")
const newController = require("./src/controllers/newController")
const homeController = require("./src/controllers/homeController")
const profileController = require("./src/controllers/profileController")
const erro404Controller = require("./src/controllers/erro404Controller")
const contatoController = require("./src/controllers/contatoController")
const loginMiddleware = require("./src/middlewares/loginMiddleware")


route.get("/contato/delete/:id", loginMiddleware.loginRequered, contatoController.delete)
route.get("/contato/edit/:id", loginMiddleware.loginRequered, contatoController.editContato)
route.post("/contato/edit/:id", loginMiddleware.loginRequered, contatoController.edit)
route.get("/contato", loginMiddleware.loginRequered, contatoController.contato)
route.post("/contato", loginMiddleware.loginRequered, contatoController.register)
route.get("/error", erro404Controller.erro)
route.get("/logout", loginMiddleware.loginRequered, loginController.logout)
route.get("/login", loginMiddleware.isLogin, loginController.loginHome)
route.post("/login", loginMiddleware.isLogin, loginController.login)
route.get("/new", loginMiddleware.isLogin, newController.new)
route.post("/new", loginMiddleware.isLogin, newController.register)
route.get("/", homeController.home)
route.get("/profile", profileController.profile)
module.exports = route